### ISSUE TITLE
[Feature]: Enable pod/service monitor for metrics endpoint

### ISSUE THREAD

**Issue by blake-hamm** [ROCm/gpu-operator#106]
### Suggestion Description

I've been struggling to leverage the current implementation of the metrics exporter. I'm finding it hard to consume the metrics from within the cluster using a service or pod monitor. Here are two approaches that could fix it:

- Add explicit port config to the metrics daemonset (currently there is not port)
- Name port on `gpu-operator-metrics-exporter` svc and enable labels (currently the port is unnamed and there is no way to label except through patching)

If the first option is addressed, then a pod monitor could be deployed. If the second option is addressed, then a service monitor could be deployed.

I'm having a hard time following the code base and I'm not sure how the exporter daemonset is deployed. With some direction, I would be happy to start looking into and testing a fix.

### Operating System

Debian 12

### GPU

Radeon 7900xtx

### ROCm Component

Metrics exporter

**Comment by blake-hamm** [comment]
I was able to get it working with this config:
```yaml
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: gpu-operator
  namespace: gpu
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  driver:
    enable: false
    blacklist: true
  devicePlugin:
    devicePluginImage: rocm/k8s-device-plugin:latest
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest
    enableNodeLabeller: true
  metricsExporter:
    enable: true
    rbacConfig:
      enable: false
      disableHttps: true
  testRunner:
    enable: true
  selector:
    gpu: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-operator-metrics-exporter-custom
  namespace: gpu
  labels:
    app.kubernetes.io/name: metrics-exporter-custom
    daemonset-name: gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: metrics-exporter
    daemonset-name: gpu-operator
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpu-operator-metrics-exporter-monitor-custom
  namespace: gpu
  labels:
    release: monitor
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-exporter-custom
      daemonset-name: gpu-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
```
