### ISSUE TITLE
[Feature]: Change nodeAffinity in OLM deployment to not require master or control plane labels on nodes.

### ISSUE THREAD

**Issue by bhpratt** [ROCm/gpu-operator#129]
### Suggestion Description

Some installations of managed OpenShift such as Hypershift: https://github.com/openshift/hypershift deploy a hosted control plane that is segmented from the data plane. In these installs, the worker nodes do not have the `node-role.kubernetes.io/control-plane` or `node-role.kubernetes.io/master` labels. Because the worker nodes do not have these labels, operators, such as the AMD GPU Operator that include requiredDuringSchedulingIgnoredDuringExecution such as:

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
```

Will not run out of the box. Suggestion is to change the nodeAffinity to preferredDuringSchedulingIgnoredDuringExecution or expose a method for the end user to set their own nodeAffinity setting to accomodate these types of OpenShift installs.

**Comment by yansun1996** [comment]
Hi @bhpratt thanks for the suggestion for deploying AMD GPU operator on a hosted control plane, we will evaluate your PR and get back to you.

**Comment by bhpratt** [comment]
Confirmed in 1.21. Thanks again.

OOC - I didn't see the change in this codebase. I take it there's an internal codebase where the change was made?

```
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            weight: 1
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            weight: 1
```
