### ISSUE TITLE
[Feature]: Tolerations for NFD workers

### ISSUE THREAD

**Issue by OguzPastirmaci** [ROCm/gpu-operator#149]
### Suggestion Description

We have default taints added to GPU nodes. The main `values.yaml` does not have the keys to add tolerations for NFD workers.

**Comment by yansun1996** [comment]
Hi @OguzPastirmaci yep this is a good suggestion, let us pull some subchart ```values.yaml``` fields to the main ```values.yaml```

**Comment by yansun1996** [comment]
Hi @OguzPastirmaci the commit to expose NFD worker's toleration in main ```values.yaml``` was already merged into main branch, https://github.com/ROCm/gpu-operator/blob/b31791e185345e63061eefcf925a68313d80a600/helm-charts-k8s/values.yaml#L5-L10, the upcoming v1.3.0 release helm chart will have the change included.

As for existing released helm chart, you can still configure it by using ```--set``` option or prepare customized ```customized_values.yaml``` during executing helm install commands.

```yaml
# NFD related configs
node-feature-discovery:
  # -- Set to true/false to enable/disable the installation of node feature discovery (NFD) operator
  enabled: true
  worker:
    tolerations:
      - key: "amd-dcm"
        operator: "Equal"
        value: "up"
        effect: "NoExecute"
```
