### ISSUE TITLE
[Feature]: Enable debian12 support

### ISSUE THREAD

**Issue by m3co-code** [ROCm/gpu-operator#207]
### Suggestion Description

Hi. Is it possible to enable driver installation for debian12? 🤞 The ROCm drivers should be ready according to the [matrix](https://rocm.docs.amd.com/en/latest/compatibility/compatibility-matrix.html). I didn't find one for the device plugin though, would be keen to learn if you'd know of any concerns re debian12 support on the plugin side.

Thank you so much in advance :)

--- 

Log I get when I tried the operator on a debian12 with a mi300x 
```
1 controller.go:341] "Reconciler error" err="failed to handle build ConfigMap for DeviceConfig kube-amd-gpu/gpu-operator: invalid node worker-3, err: OS: debian gnu/linux 12 (bookworm) not supported. Should be one of [ubuntu coreos rhel red hat redhat]" logger="amd-gpu" controller="DriverAndPluginReconciler" controllerGroup="amd.com" controllerKind="DeviceConfig" DeviceConfig="kube-amd-gpu/gpu-operator" namespace="kube-amd-gpu" name="gpu-operator" reconcileID="fd2a95ec-3f38-4fe0-8faf-afdd4ea06c18"
```

```
  driver:
    enable: true
    blacklist: true
  devicePlugin:
    devicePluginImage: rocm/k8s-device-plugin:v1.31.0.6
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-v1.31.0.6
```
