### ISSUE TITLE
[Issue]: init containers images urls can't be changed

### ISSUE THREAD

**Issue by boniek83** [ROCm/gpu-operator#55]
### Problem Description

This makes it impossible for it to work inside air-gapped environments. Example:
Init Containers:
  driver-init:
    Container ID:  
    Image:         docker.io/busybox:1.36

### Operating System

Alma 8.10

### CPU

AMD EPYC 9454

### GPU

MI300X

### ROCm Version

6.2.4

**Comment by sajmera-pensando** [comment]
Hi @boniek83 , in the code there is no registry specified in the busy box URL (the URL used is "busybox:1.36"), so its picking the default registry from your k8s environment which happens to be docker.io in Vanilla K8s. You can change the default registry of your K8s environment to be the private registry of the air-gapped environment.

Thanks.

**Comment by boniek83** [comment]
What's the point of having ability to change every other image url except for init images then? I would prefer not to change cluster defaults as I'm not the only that is using it and I don't know how it might impact other workloads.

**Comment by sajmera-pensando** [comment]
ok, Thanks Rafal. Please let us discuss this requirement and get back to you.

**Comment by farshadghodsian** [comment]
@boniek83 The new version of the GPU Operator, v1.2.0, now supports changing the base initContainer image. This can be specified in the DeviceConfig under `spec.commonConfig.initContainerImage`.

```yaml
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: gpu-operator
  namespace: kube-amd-gpu
spec:
  commonConfig:
    initContainerImage: busybox:1.36 # This is the default if an alternate image is not specified
```
