### ISSUE TITLE
[Issue]: Fail to deploy Device Plugin with ROCm version 6.3.3 and 6.3.4

### ISSUE THREAD

**Issue by bdattoma** [ROCm/gpu-operator#66]
### Problem Description

After upgrading from ROCm 6.2.2 to 6.3.3, by editing the `DeviceConfig` CR, and waiting for the driver to be built, the `device-plugin` pod (ns: kube-amd-gpu) fails to indentify the GPU node

Extracted from the pod logs:
```
I0311 09:54:20.038972 1 amdgpu.go:139] /sys/devices/platform/amdgpu_xcp_7
I0311 09:54:20.038977 1 amdgpu.go:139] /sys/devices/platform/amdgpu_xcp_8
I0311 09:54:20.038982 1 amdgpu.go:139] /sys/devices/platform/amdgpu_xcp_9
I0311 09:54:20.038987 1 plugin.go:136] Found 0 AMDGPUs
```

Versions:
- OpenShift: 4.15.35
- AMD GPU Operator: 1.1.1 
- KMM: 2.3.0

### Operating System

Red Hat Enterprise Linux CoreOS  415.92.202409241719-0

### CPU

Intel(R) Xeon(R) Platinum 8480C

### GPU

AMD Instinct MI300X

### ROCm Version

6.3.3

### Steps to Reproduce

1. Install AMD GPU operator stack on OpenShift
2. Configure AMD operator (i.e., DevicePlugin custom resource) to use ROCm 6.2.2
3. Wait until drivers are built (i.e., image stream and related tag)
4. Wait until KMM loads the driver
5. Wait until the device-plugin pod detects the GPUs successfully
```
I0307 23:29:14.533973 1 plugin.go:136] Found 8 AMDGPUs
I0307 23:29:14.720194 1 plugin.go:156] Watching GPU with bus ID: 0003:00:00.0 NUMA Node: [0]
I0307 23:29:14.720241 1 plugin.go:156] Watching GPU with bus ID: 0004:00:00.0 NUMA Node: [0]
....
I0308 06:57:36.678832 1 plugin.go:235] Allocating device ID: 0008:00:00.0
```
6. Edit DevicePlugin CR to move from ROCm 6.2.2 to 6.3.3 (or 6.3.4)
7. repeat steps from 3 to 5

Alternative we've tried: re-create DevicePlugin CR instead of upgrading it. Same result

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

```
rocminfo
ROCk module version 6.10.5 is loaded
Unable to open /dev/kfd read-write: No such file or directory
Failed to get user name to check for video group membership
```

### Additional Information
- we have not tried versions < 6.3.3 yet
- Device Plugin CR:
```
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: test
  namespace: kube-amd-gpu
spec:
  devicePlugin:
    devicePluginImage: 'rocm/k8s-device-plugin:latest'
    enableNodeLabeller: true
    nodeLabellerImage: 'rocm/k8s-device-plugin:labeller-latest'
  driver:
    enable: true
    version: 6.3.3
  selector:
    feature.node.kubernetes.io/pci-1002.present: 'true'
```

**Comment by sajmera-pensando** [comment]
Thanks for reporting this issue. We are looking into it.

**Comment by bdattoma** [comment]
> Hi [@bdattoma](https://github.com/bdattoma) , we would need the full log of the device plugin pod (not just the few lines attached in the description)
> 
> Additionally, we would need info from the /sys folder as we were not able to reproduce the issue. Would it be possible to tar everything under the /sys folder on the gpu node and attach it here somehow?
> 
> Specifically, we would like the following outputs when in problem state:
> 
> 1. Whether 8 folders with pci Id's are present in `/sys/module/amdgpu/drivers/pci:amdgpu/` corresponding to the 8 gpus
>    (Output of files under `/sys/module/amdgpu/drivers/pci:amdgpu/` )
> 2. Contents of this `/sys/class/kfd/kfd/topology/nodes/0/properties` file for each of the nodes under `/sys/class/kfd/topology/nodes`.
>    (That is, contents of  `/sys/class/kfd/kfd/topology/nodes/0/properties`, `/sys/class/kfd/kfd/topology/nodes/1/properties`, etc.)
> 
> Output of 1) and 2) are required if we are not able to collect the entire /sys folder into a tar


Hello @sriram-30 , I'll be back to you as soon as I can, I need to try the upgrade once again. 

So, you were able to upgrade from 6.2.2 to 6.3.3 using the same DeviceConfig CR I published in the issue description?

**Comment by sriram-30** [comment]
> > Hi [@bdattoma](https://github.com/bdattoma) , we would need the full log of the device plugin pod (not just the few lines attached in the description)
> > Additionally, we would need info from the /sys folder as we were not able to reproduce the issue. Would it be possible to tar everything under the /sys folder on the gpu node and attach it here somehow?
> > Specifically, we would like the following outputs when in problem state:
> > 
> > 1. Whether 8 folders with pci Id's are present in `/sys/module/amdgpu/drivers/pci:amdgpu/` corresponding to the 8 gpus
> >    (Output of files under `/sys/module/amdgpu/drivers/pci:amdgpu/` )
> > 2. Contents of this `/sys/class/kfd/kfd/topology/nodes/0/properties` file for each of the nodes under `/sys/class/kfd/topology/nodes`.
> >    (That is, contents of  `/sys/class/kfd/kfd/topology/nodes/0/properties`, `/sys/class/kfd/kfd/topology/nodes/1/properties`, etc.)
> > 
> > Output of 1) and 2) are required if we are not able to collect the entire /sys folder into a tar
> 
> Hello [@sriram-30](https://github.com/sriram-30) , I'll be back to you as soon as I can, I need to try the upgrade once again.
> 
> So, you were able to upgrade from 6.2.2 to 6.3.3 using the same DeviceConfig CR I published in the issue description?

Sure, no problem! You can give us the info once you're able to reproduce the issue. 

Yep, we were able to upgrade to the version with the same CR without any issue. Creating CR for the version instead of upgrading also worked for us.

**Comment by bdattoma** [comment]
> > > Hi [@bdattoma](https://github.com/bdattoma) , we would need the full log of the device plugin pod (not just the few lines attached in the description)
> > > Additionally, we would need info from the /sys folder as we were not able to reproduce the issue. Would it be possible to tar everything under the /sys folder on the gpu node and attach it here somehow?
> > > Specifically, we would like the following outputs when in problem state:
> > > 
> > > 1. Whether 8 folders with pci Id's are present in `/sys/module/amdgpu/drivers/pci:amdgpu/` corresponding to the 8 gpus
> > >    (Output of files under `/sys/module/amdgpu/drivers/pci:amdgpu/` )
> > > 2. Contents of this `/sys/class/kfd/kfd/topology/nodes/0/properties` file for each of the nodes under `/sys/class/kfd/topology/nodes`.
> > >    (That is, contents of  `/sys/class/kfd/kfd/topology/nodes/0/properties`, `/sys/class/kfd/kfd/topology/nodes/1/properties`, etc.)
> > > 
> > > Output of 1) and 2) are required if we are not able to collect the entire /sys folder into a tar
> > 
> > 
> > Hello [@sriram-30](https://github.com/sriram-30) , I'll be back to you as soon as I can, I need to try the upgrade once again.
> > So, you were able to upgrade from 6.2.2 to 6.3.3 using the same DeviceConfig CR I published in the issue description?
> 
> Sure, no problem! You can give us the info once you're able to reproduce the issue.
> 
> Yep, we were able to upgrade to the version with the same CR without any issue. Creating CR for the version instead of upgrading also worked for us.

Hello, I reproduced the upgrade issue.

These are the requested info:

1. folders with pci Id's are present in /sys/module/amdgpu/drivers/pci:amdgpu/. With 6.2.2 there were the expected 8 folders, one for each gpu. After the upgrade to 6.3.3 there aren't any
```sh-5.1# ls /sys/module/amdgpu/drivers/pci:amdgpu/
bind  module  new_id  remove_id  uevent  unbind
```
2. Contents of this /sys/class/kfd/kfd/topology/nodes/X/properties. Only 2 nodes found
```
sh-5.1# cat /sys/class/kfd/kfd/topology/nodes/0/properties
cpu_cores_count 48
simd_count 0
mem_banks_count 1
caches_count 0
io_links_count 1
p2p_links_count 0
cpu_core_id_base 0
simd_id_base 0
max_waves_per_simd 0
lds_size_in_kb 0
gds_size_in_kb 0
num_gws 0
wave_front_size 0
array_count 0
simd_arrays_per_engine 0
cu_per_simd_array 0
simd_per_cu 0
max_slots_scratch_cu 0
gfx_target_version 0
vendor_id 0
device_id 0
location_id 0
domain 0
drm_render_minor 0
hive_id 0
num_sdma_engines 0
num_sdma_xgmi_engines 0
num_sdma_queues_per_engine 0
num_cp_queues 0
max_engine_clk_ccompute 2000

-----

sh-5.1# cat /sys/class/kfd/kfd/topology/nodes/1/properties
cpu_cores_count 48
simd_count 0
mem_banks_count 1
caches_count 0
io_links_count 1
p2p_links_count 0
cpu_core_id_base 64
simd_id_base 0
max_waves_per_simd 0
lds_size_in_kb 0
gds_size_in_kb 0
num_gws 0
wave_front_size 0
array_count 0
simd_arrays_per_engine 0
cu_per_simd_array 0
simd_per_cu 0
max_slots_scratch_cu 0
gfx_target_version 0
vendor_id 0
device_id 0
location_id 0
domain 0
drm_render_minor 0
hive_id 0
num_sdma_engines 0
num_sdma_xgmi_engines 0
num_sdma_queues_per_engine 0
num_cp_queues 0
max_engine_clk_ccompute 2000
```

Other info:
1. followed https://instinct.docs.amd.com/projects/gpu-operator/en/release-v1.1.0/drivers/upgrading.html#option-a-direct-update-recommended to update the KMM label on the GPU node
2. the DeviceConfig CR reports 6.3.3 as loaded driver
3. I'll send you the full logs of device plugin privately

**Comment by dtrifiro** [comment]
Hi @sriram-30,

we tried doing a fresh install of the AMD GPU Operator (uninstall and reinstall of version 1.1.1).

0. Uninstall operator
1. Reinstall operator from operatorhub (v1.1.1)
2. Create a new `DeviceConfig` with **ROCm 6.3.3**:

```yaml
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: deviceconfig
  namespace: kube-amd-gpu
spec:
  driver:
    blacklist: true
    enable: true
    version: 6.3.3
  selector:
    feature.node.kubernetes.io/pci-1002.present: 'true'
```
3. Wait for the for the operator to finish the kernel modules build (`pod/deviceconfig-build-xxxxxx-build`)
4. Once it finishes, the `kmm` pod starts and tries to load the kernel module:

```
$ kubectl logs -f pod/kmm-worker-ods-az-amd-01-pool-r5-pd4qn-gpu2-westus-5jgmp-deviceconfig
Defaulted container "worker" out of: worker, image-extractor (init)
I0415 10:34:47.060261       1 funcs_kmod.go:12] "Starting worker" logger="kmm-worker" version="2.3.0" git commit="b57037e"
I0415 10:34:47.060314       1 funcs_kmod.go:24] "Reading config" logger="kmm-worker" path="/etc/kmm-worker/config.yaml"
I0415 10:34:47.060654       1 worker.go:76] "preparing firmware for loading" logger="kmm-worker" image directory="/tmp/firmwareDir/updates" host mount directory="/var/lib/firmware"
I0415 10:34:47.082232       1 modprobe.go:33] "Running modprobe" logger="kmm-worker" command="/usr/sbin/modprobe -vd /tmp/opt amdgpu"
```

There's a long wait after this, and if we go into the node itself and follow kernel logs with `dmesg -wH`, we get a ton of  stack traces and a spam of the following line for a long time:

```
[drm:amdgpu_gmc_flush_gpu_tlb [amdgpu]] *ERROR* Timeout waiting for VM flush ACK!
```

After this has been going on for a while, we finally something else:

```
[  +0.003940] amdgpu: probe of 0003:00:00.0 failed with error -22
[  +0.050636] [drm] amdgpu: ttm finalized
[  +0.001667] amdgpu 0004:00:00.0: enabling device (0000 -> 0002)
[  +3.237583] [drm] initializing kernel modesetting (IP DISCOVERY 0x1002:0x74B5 0x1002:0x74A1 0x00).
[  +0.000468] [drm] register mmio base: 0x40E00000
[  +0.000003] [drm] register mmio size: 2097152
[  +0.007775] [drm] host supports REQ_INIT_DATA handshake
[  +0.000002] [drm] MCBP is enabled
[  +0.009939] [drm] add ip block number 0 <soc15_common>
[  +0.000003] [drm] add ip block number 1 <gmc_v9_0>
[  +0.000001] [drm] add ip block number 2 <psp>
[  +0.000001] [drm] add ip block number 3 <vega20_ih>
[  +0.000001] [drm] add ip block number 4 <smu>
[  +0.000001] [drm] add ip block number 5 <gfx_v9_4_3>
[  +0.000001] [drm] add ip block number 6 <sdma_v4_4_2>
[  +0.000002] [drm] add ip block number 7 <vcn_v4_0_3>
[  +0.000001] [drm] add ip block number 8 <jpeg_v4_0_3>
[  +0.004948] amdgpu 0004:00:00.0: amdgpu: Fetched VBIOS from VRAM BAR
[  +0.000004] amdgpu: ATOM BIOS: 113-MI3SRIOV-001
[  +0.000319] amdgpu 0004:00:00.0: amdgpu: Trusted Memory Zone (TMZ) feature not supported
[  +0.000209] amdgpu 0004:00:00.0: amdgpu: MEM ECC is active.
[  +0.000002] amdgpu 0004:00:00.0: amdgpu: SRAM ECC is active.
[  +0.000016] amdgpu 0004:00:00.0: amdgpu: RAS INFO: ras initialized successfully, hardware ability[18127] ras_mask[18127]
[  +0.000030] [drm] vm size is 262144 GB, 4 levels, block size is 9-bit, fragment size is 9-bit
[  +0.000009] amdgpu 0004:00:00.0: amdgpu: VRAM: 196048M 0x0000020000000000 - 0x0000022FDCFFFFFF (196048M used)
[  +0.000002] amdgpu 0004:00:00.0: amdgpu: GART: 512M 0x0000000000000000 - 0x000000001FFFFFFF
[  +0.000019] amdgpu 0004:00:00.0: amdgpu: Not able to detect NPS mode, fall back to NPS1
[  +0.004593] [drm] Detected VRAM RAM=196048M, BAR=262144M
[  +0.000003] [drm] RAM width 8192bits HBM
[  +0.001341] [drm] amdgpu: 196048M of VRAM memory ready
[  +0.000003] [drm] amdgpu: 932333M of GTT memory ready.
[  +0.000020] [drm] GART: num cpu pages 131072, num gpu pages 131072
[  +0.124500] [drm] PCIE GART of 512M enabled.
[  +0.000002] [drm] PTB located at 0x0000020000100000
[  +0.067792] [drm] Found VCN firmware Version ENC: 1.23 DEC: 9 VEP: 0 Revision: 9
[  +0.003985] [drm] MM table gpu addr = 0x200007a1000, cpu addr = 00000000d79608fb.
[  +0.124421] amdgpu 0004:00:00.0: amdgpu: smu driver if version = 0x08042024, smu fw if version = 0x08042027, smu fw program = 0, smu fw version = 0x00556b01 (85.107.1)
[  +0.000004] amdgpu 0004:00:00.0: amdgpu: SMU driver if version not matched
[  +0.001588] amdgpu 0004:00:00.0: amdgpu: SMU is initialized successfully!
[  +0.154616] amdgpu 0004:00:00.0: amdgpu: register is not in range, rlcg failed to program reg: 0x0f828
[  +0.003756] [drm:amdgpu_device_ip_init [amdgpu]] *ERROR* hw_init of IP block <gfx_v9_4_3> failed -22
[  +0.003646] amdgpu 0004:00:00.0: amdgpu: amdgpu_device_ip_init failed
[  +0.012556] amdgpu 0004:00:00.0: amdgpu: Fatal error during GPU init
[  +0.002898] amdgpu 0004:00:00.0: amdgpu: amdgpu: finishing device.
[Apr15 10:43] amdgpu 0004:00:00.0: amdgpu: Doesn't get msg:1 from pf, error=-62
[  +0.003909] [drm] clean up the vf2pf work item
....
```

This is followed by a long list of stack traces, and then the `*ERROR* Timeout waiting for VM flush ACK!` message starts printing again.

This process is repeated several times (one for each GPU?) until it finally completes, although no GPUs are actually available on the node. `lsmod` shows some kernel drivers loaded:

```
sh-5.2# lsmod |grep amd
amdgpu              13721600  1
amddrm_ttm_helper      16384  1 amdgpu
amdttm                 90112  2 amdgpu,amddrm_ttm_helper
amdxcp                 16384  1 amdgpu
amddrm_buddy           20480  1 amdgpu
amd_sched              53248  1 amdgpu
amdkcl                 45056  3 amd_sched,amdttm,amdgpu
i2c_algo_bit           16384  1 amdgpu
drm_display_helper    172032  1 amdgpu
drm_kms_helper        192512  5 drm_display_helper,hyperv_drm,amdgpu
drm                   581632  12 drm_kms_helper,amd_sched,amdttm,drm_shmem_helper,drm_display_helper,hyperv_drm,amdgpu,amddrm_buddy,amdkcl,amddrm_ttm_helper,amdxcp
```

Attached you will find the full dmesg log:
[dmesg_loaded.log](https://github.com/user-attachments/files/19756297/dmesg_loaded.log)

**Comment by bdattoma** [comment]
Hello @sriram-30 , I could test today with the new operator v1.2.0 which support the ROCm upgrade with automatic node reboot.

I retried from 6.2.2 to 6.3.3 with the following DeviceConfig CR:
```
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  finalizers:
    - amd.node.kubernetes.io/deviceconfig-finalizer
  name: <name>
  namespace: <namespace>
spec:
  devicePlugin:
    devicePluginImage: 'rocm/k8s-device-plugin:latest'
    enableNodeLabeller: true
    nodeLabellerImage: 'rocm/k8s-device-plugin:labeller-latest'
  driver:
    blacklist: true
    enable: true
    upgradePolicy:
      enable: true
      maxParallelUpgrades: 1
      maxUnavailableNodes: 40%
      rebootRequired: true
    version: 6.3.3
  selector:
    feature.node.kubernetes.io/pci-1002.present: 'true'
status:
  conditions:
    - lastTransitionTime: '2025-04-18T15:32:25Z'
      message: ''
      reason: OperatorReady
      status: 'True'
      type: Ready
  devicePlugin:
    availableNumber: 1
    desiredNumber: 1
    nodesMatchingSelectorNumber: 1
  driver:
    availableNumber: 1
    desiredNumber: 1
    nodesMatchingSelectorNumber: 1
  metricsExporter: {}
  nodeModuleStatus:
   <node>:
      bootId: <...>
      containerImage: '<....>-6.3.3'
      kernelVersion: 5.14.0-284.86.1.el9_2.x86_64
      lastTransitionTime: '2025-04-18 16:19:04 +0000 UTC'
      status: Upgrade-Complete
      upgradeStartTime: '2025-04-18 16:01:31 UTC'
  observedGeneration: 4
```

The DevicePlugin pod logs report:
```
[....]
I0418 16:19:10.303304 1 plugin.go:173] Found 0 AMDGPUs
W0418 16:19:40.328807 1 plugin.go:150] No GPU nodes found via properties
W0418 16:20:10.329486 1 plugin.go:150] No GPU nodes found via properties
W0418 16:20:40.330296 1 plugin.go:150] No GPU nodes found via properties
```

The 2 output you requested earlier:
```
sh-5.1# cat /sys/class/kfd/kfd/topology/nodes/0/properties
cpu_cores_count 48
simd_count 0
mem_banks_count 1
caches_count 0
io_links_count 1
p2p_links_count 0
cpu_core_id_base 0
simd_id_base 0
max_waves_per_simd 0
lds_size_in_kb 0
gds_size_in_kb 0
num_gws 0
wave_front_size 0
array_count 0
simd_arrays_per_engine 0
cu_per_simd_array 0
simd_per_cu 0
max_slots_scratch_cu 0
gfx_target_version 0
vendor_id 0
device_id 0
location_id 0
domain 0
drm_render_minor 0
hive_id 0
num_sdma_engines 0
num_sdma_xgmi_engines 0
num_sdma_queues_per_engine 0
num_cp_queues 0
max_engine_clk_ccompute 2000

sh-5.1# cat /sys/class/kfd/kfd/topology/nodes/1/properties
cpu_cores_count 48
simd_count 0
mem_banks_count 1
caches_count 0
io_links_count 1
p2p_links_count 0
cpu_core_id_base 64
simd_id_base 0
max_waves_per_simd 0
lds_size_in_kb 0
gds_size_in_kb 0
num_gws 0
wave_front_size 0
array_count 0
simd_arrays_per_engine 0
cu_per_simd_array 0
simd_per_cu 0
max_slots_scratch_cu 0
gfx_target_version 0
vendor_id 0
device_id 0
location_id 0
domain 0
drm_render_minor 0
hive_id 0
num_sdma_engines 0
num_sdma_xgmi_engines 0
num_sdma_queues_per_engine 0
num_cp_queues 0
max_engine_clk_ccompute 2000
```
