### ISSUE TITLE
[Issue]: Fail to blacklist in-tree driver when creating MachineConfig manually

### ISSUE THREAD

**Issue by bdattoma** [ROCm/gpu-operator#93]
### Problem Description

When using [Method 1](https://github.com/ROCm/gpu-operator/blob/main/docs/drivers/installation.md#method-1---manual-blacklist) from documentation to blacklist in-tree driver (in order to install ROCm), the AMD GPU operator keeps deleting `/etc/modprobe.d/blacklist-amdgpu.conf` file.

### Operating System

OpenShift 4.17.19 - Red Hat Enterprise Linux CoreOS 417.94.202502251300-0

### CPU

Intel(R) Xeon(R) Platinum 8480C

### GPU

AMD Instinct MI300X

### ROCm Version

6.2.2

### Steps to Reproduce

1. create MachineConfig like in docs https://instinct.docs.amd.com/projects/gpu-operator/en/release-v1.1.0/installation/openshift-olm.html#create-blacklist-for-installing-out-of-tree-kernel-module
2. check if `/etc/modprobe.d/blacklist-amdgpu.conf` file exists in the GPU node (_it should_)
3. create DeviceConfig CR like https://instinct.docs.amd.com/projects/gpu-operator/en/release-v1.1.0/installation/openshift-olm.html#create-deviceconfigWe use the following:
```
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: device-config-test
  namespace: test-namespace
spec:
  devicePlugin:
    devicePluginImage: 'rocm/k8s-device-plugin:latest'
    enableNodeLabeller: true
    nodeLabellerImage: 'rocm/k8s-device-plugin:labeller-latest'
  driver:
    enable: true
    version: 6.2.2
  selector:
    feature.node.kubernetes.io/pci-1002.present: 'true'
```
3. check if `/etc/modprobe.d/blacklist-amdgpu.conf` file exists in the GPU node (_it should_ - _it does not_)
4. check MCO daemon pod logs (i.e., `machine-config-daemon-xyz` in NS `openshift-machine-config-operator`)
```
E0319 14:25:55.975962    4887 writer.go:226] Marking Degraded due to: unexpected on-disk state validating against rendered-worker-758c253b5ec87d2f73d3448f9580e7ad: could not stat file "/etc/modprobe.d/blacklist-amdgpu.conf": lstat /etc/modprobe.d/blacklist-amdgpu.conf: no such file or directory
```
5. after the ROCm image finished building in the internal registry, we also saw KMM controller pod (`kmm-operator-controller-xyz` in NS `openshift-kmm`) reporting the following error:
```
E0319 14:31:14.057636       1 controller.go:329] "Reconciler error" err="failed to reconcile module kube-amd-gpu/dc-internal-registry config: failed to verify that image image-registry:5000/kube-amd-gpu/amdgpu_kmod:coreos-417.94-5.14.0-427.57.1.el9_4.x86_64-6.2.2 exists: could not check if the image is available: could not get image image-registry:5000/kube-amd-gpu/amdgpu_kmod:coreos-417.94-5.14.0-427.57.1.el9_4.x86_64-6.2.2: failed to get manifest stream from image image-registry:5000/kube-amd-gpu/amdgpu_kmod:coreos-417.94-5.14.0-427.57.1.el9_4.x86_64-6.2.2: failed to get crane manifest from image image-registry:5000/kube-amd-gpu/amdgpu_kmod:coreos-417.94-5.14.0-427.57.1.el9_4.x86_64-6.2.2: Get \"https://image-registry:5000/v2/\": dial tcp: lookup image-registry on <IP>: no such host" logger="kmm" controller="ModuleNMCReconciler" controllerGroup="kmm.sigs.x-k8s.io" controllerKind="Module" Module="kube-amd-gpu/dc-internal-registry" namespace="kube-amd-gpu" name="dc-internal-registry" reconcileID="7e927412-b4d7-4688-8c43-00946fb2bbc0"
```

### Additional Information

- we found this line of code https://github.com/ROCm/gpu-operator/blob/main/internal/nodelabeller/nodelabeller.go#L155 which makes us suspect it's interefering with the manual driver blacklist method
- to try workarounding the issue, we deleted the MachineConfig and blacklisted the driver using DeviceConfig option like https://github.com/ROCm/gpu-operator/blob/main/docs/drivers/installation.md#install-out-of-tree-amd-gpu-drivers-with-operator
- Although in this way the blacklist file is not getting removed from the node, MCO operator does not seem happy and keeps printing this error in the logs
```
E0321 10:03:49.241244 444615 on_disk_validation.go:251] content mismatch for file "/etc/modprobe.d/blacklist-amdgpu.conf" (-want +got):
149
```
- Operator stack versions
KMM operator version: 2.3.0
AMD GPU operator version: 1.1.1

**Comment by yansun1996** [comment]
thanks for the reporting @bdattoma , we're investigating the issue and will push a fix to the incoming release.

**Comment by yansun1996** [comment]
Hi @bdattoma , 
This issue post consists of 2 issues:
1. Operator controller failed to detect that the cluster is an OpenShift cluster. I raised a PR to optimize the detection mechanism.
2. Driver Blacklist issue when using the OpenShift MachineConfigOperator (MCO)

As for the 2nd issue, can you provide these details it is applicable ? It would be helpful for our fix on the issue.

1. Are you using single node cluster ? or multiple node cluster ? 
2. Could you please provide your MCO YAML manifest here ? 
3. In the OpenShift instruction docs https://instinct.docs.amd.com/projects/gpu-operator/en/latest/installation/openshift-olm.html#create-blacklist-for-installing-out-of-tree-kernel-module , we mentioned that single node cluster and multiple node cluster require different node selector for MCO custom resource, could you please check whether you setup the right node label selector for your MCO custom resource ?

**Comment by bdattoma** [comment]
> can you provide these details it is applicable ? It would be helpful for our fix on the issue.

Hello @yansun1996 thanks for your reply and the PR for issue 1.

About your questions:
1. This is a mixed scenario: the cluster was created as SNO and we added, after provision, a worker node with AMD MI300X GPU. 
2. did you mean the MachineConfig custom resource? 
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: amdgpu-module-blacklist
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: "/etc/modprobe.d/blacklist-amdgpu.conf"
          mode: 420
          overwrite: true
          contents:
            source: "data:text/plain;base64,YmxhY2tsaXN0IGFtZGdwdQo="
```
3. Given that the AMD GPU is attached to a worker node, I think the label should remain `machineconfiguration.openshift.io/role: worker` instead of using master, otherwise the blacklist won't happen on GPU node. Wdyt?
